services:
  playgroup-one:
    build:
      context: .
      dockerfile: Dockerfile
    # image: playgroup-one:local   # ❌ remove this when building in a Stack
    container_name: playgroup-one
    environment:
      TZ: ${TZ:-America/Chicago}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      PASSWORD: ${PASSWORD}
      PLAYGROUP_URL: ${PLAYGROUP_URL}
      PLAYGROUP_SHA256: ${PLAYGROUP_SHA256:-}
    ports:
      - "${HTTP_PORT:-3000}:3000"
    tmpfs:
      - /opt/app:rw,noexec,nosuid,nodev,size=256m
    volumes:
      - data:/config
    restart: unless-stopped

volumes:
  data:
