services:
  playgroup-one:
    build:
      context: .
    container_name: playgroup-one
    environment:
      TZ: ${TZ:-America/Chicago}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      PASSWORD: ${PASSWORD}
      PLAYGROUP_URL: ${PLAYGROUP_URL}
      PLAYGROUP_SHA256: ${PLAYGROUP_SHA256:-}
    ports:
      - "${HTTP_PORT:-3000}:3000"
    volumes:
      - config:/config:rw           # local docker volume (NOT NFS)
      - appcache:/opt/app-cache:rw
    restart: unless-stopped

volumes:
  config:    # <-- local volume managed by Docker
  appcache:
